use clap::{App, Arg};

pub fn config() -> App<'static, 'static> {
    App::new("HTTP Shell Executor")
        .version("0.1")
        .author("Ganlv <ganlvtech@qq.com>")
        .about("A simple server serving shell script.")
        .arg(Arg::with_name("listen")
            .short("l")
            .long("listen")
            .value_name("IP:PORT")
            .default_value("127.0.0.1:80")
            .help("Listening IP and port")
            .takes_value(true))
        .arg(Arg::with_name("public")
            .long("public")
            .value_name("DIR")
            .help("Static files directory path")
            .default_value("./public/")
            .takes_value(true))
        .arg(Arg::with_name("public-index")
            .long("public-index")
            .value_name("FILE")
            .default_value("index.html")
            .help("Index filename")
            .takes_value(true))
        .arg(Arg::with_name("scripts")
            .long("scripts")
            .value_name("DIR")
            .default_value("./scripts/")
            .help("Shell scripts directory path")
            .takes_value(true))
}