name: Build/publish release

on: [push, pull_request]

jobs:
  publish:
    name: Binary ${{ matrix.target }} (on ${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: --locked --release
          strip: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/http-shell-executor${{ matrix.ext }}

      - name: Rename binary
        shell: bash
        run: mv "target/${{ matrix.target }}/release/http-shell-executor${{ matrix.ext }}" "target/${{ matrix.target }}/release/http-shell-executor-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.ext }}"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/http-shell-executor-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.ext }}
